name: Node.js Public Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  DATAUNLOCKER_ENV: ${{ secrets.DATAUNLOCKER_ENV }}
  DATAUNLOCKER_ID: ${{ secrets.DATAUNLOCKER_ID }}

jobs:
  build-test-publish:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
      - run: npm run build
      - run: npm run test

      - uses: JS-DevTools/npm-publish@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          token: ${{ env.NPM_TOKEN }}
          access: public
